
/*
 *              USAGE OF SCRIPTABLE OBJECTS AND ASSET MENU
 *              
 *   1. Right click in folder you wish to create object "Loot, class, action" etc... whatever you are going to create.
 *   
 *   2. Choose Create over the Folder Option you will see Custom options
 *
 *   3. For example... Classes -> PlayerStats -> Class Creates new Object which contains fields you can fill.
 *   
 *   4. After filling the fields you need to drag the Scriptable Object into the specific object, 
 *   
 *      for example.
 *      
 *      Class goes to MainHero_Root -> PlayerClass -> Classes  list
 *      Hero can automatically update these stats into the basestats when class selection is completed. <Not implemented yet>
 *  
 *  
 *   Good Practise is to program many systems to work with scriptable objects , 
 *      after base is done most of the playable content can be generated by dragging objects to lists
 *  
 *  Unity tutorials : 
 *  
 *      Unity Scriptable object ability system
 *      
 *      Unity Scriptable object Finite State Machine
 *      
 *      etc... 
 *
 */

